
title: Daria Minina's Homepage
page-top-title: Daria Minina
top-section-bg-text: University of Amsterdam
home-subtitle: Daria Minina&ensp;
# copyright-text: '&copy; Sen Li 2023. All Rights Reserved.'
